language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_install:
  # Manually compile the libsodium library
  - sudo apt-get update -qq
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  # Manually install libsodium, because the TravisCI image doesn't provide PHP7.2 with libsodium
  #- pecl install libsodium
  #- echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
#  - pecl channel-update pecl.php.net
  - wget http://getcomposer.org/composer.phar
  - php -d memory_limit=-1 composer.phar require php-coveralls/php-coveralls
  - php -d memory_limit=-1 composer.phar install --no-interaction
  - php -d memory_limit=-1 composer.phar dump-autoload --optimize

script:
  - mkdir -p ./tests/logs/
  - php ./vendor/bin/simple-phpunit
 
after_success:
  - travis_retry php vendor/bin/php-coveralls -v

matrix:
    fast_finish: true
    allow_failures:
      - php: "nightly"

