language: php

php:
  - 7.2
  - nightly
  
before_script:
#  - pecl channel-update pecl.php.net
  - wget http://getcomposer.org/composer.phar
  - composer require php-coveralls/php-coveralls
  - cp .env.dist .env
  - php composer.phar install --no-interaction
  - php composer.phar dump-autoload --optimize

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/simple-phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
  - travis_retry php vendor/bin/php-coveralls -v

matrix:
    fast_finish: true
    allow_failures:
      - php: "nightly"

